name: Minefetch
version: 1.1
author: WamWooWam, Snoopie
main: nya.clockwork04.Minefetch.Main
load: STARTUP
commands:
  neofetch:
    descripton: Provides a parsed output from Neofetch
    usgae: /<command>
  loadfetch:
    descripton: Provides a LagMeter like output with CPU usage and Memory usage graphs.
    usgae: /<command>