name: PowerMacInfo
version: 1.0
author: WamWooWam
main: org.wamwoowam.PowerMacInfo.Main
load: STARTUP
commands:
  system:
    description: Provides information on the current system
    usage: /<command>
  neofetch:
    descripton: Provides a parsed output from Neofetch
    usgae: /<command>